### ISSUE TITLE
Add (selected?) S2I images to mirror registry

### ISSUE THREAD

**Issue by bparry02** [dmc5179/quay-image-builder#12]
Update imageset-config to include some S2I images.

Ensure steps to configure cluster samples operator is part of post-install steps.

**Comment by dmc5179** [comment]
I created another issue for the samples operator config since these 2 things do not depend on each other.

**Comment by bparry02** [comment]
We shouldn't need individual references to each image repository in the ICSP. According to docs this should cover most of the S2I images

```
imageContentSources:
  - mirrors:
    - ip-10-20-0-26.ec2.internal:8443
    source: registry.access.redhat.com
  - mirrors:
    - ip-10-20-0-26.ec2.internal:8443
    source: registry.redhat.io
```

We will likely still have to list them in the imageset-config.yaml, however.
